# Generated by Django 6.0.7 on 2026-07-24 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='uploads/')),
                ('overall_score', models.FloatField()),
                ('eyes_score', models.FloatField()),
                ('eyebrows_score', models.FloatField()),
                ('nose_score', models.FloatField()),
                ('mouth_score', models.FloatField()),
                ('jaw_score', models.FloatField()),
                ('alignment_angle', models.FloatField()),
                ('heatmap_image', models.ImageField(upload_to='generated_images/')),
                ('overlay_image', models.ImageField(upload_to='generated_images/')),
                ('glb_model', models.FileField(upload_to='generated_models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
